version: '3'

services:
  exams:
    build:
      context: ./
      dockerfile: Dockerfile
    image: exams
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - /data/exams
    environment:
      EXAMS_SONAR_ORG: ${EXAMS_SONAR_ORG}
      EXAMS_SONAR_TOKEN: ${EXAMS_SONAR_TOKEN}
      EXAMS_DATABASE_URL: ${EXAMS_DATABASE_URL}
      EXAMS_DATABASE_USER: ${EXAMS_DATABASE_USER}
      EXAMS_DATABASE_PASSWORD: ${EXAMS_DATABASE_PASSWORD}
    links:
      - postgresql
  postgresql:
    image: postgres:alpine
    ports:
    - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${EXAMS_DATABASE}
      POSTGRES_USER: ${EXAMS_DATABASE_USER}
      POSTGRES_PASSWORD: ${EXAMS_DATABASE_PASSWORD}