version: '3.6'

services:
  database:
    image: postgres:alpine
    container_name: exams-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${EXAMS_DATABASE}
      POSTGRES_USER: ${EXAMS_DATABASE_USER}
      POSTGRES_PASSWORD: ${EXAMS_DATABASE_PASSWORD}

  redis:
    image: redis
    container_name: exams-redis
    command: redis-server --requirepass ${EXAMS_REDIS_PASSWORD}
    network_mode: "service:server"

  server:
    image: server
    container_name: exams-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports: [ "8081:8081", "6379:6379" ]
    environment:
      EXAMS_DATABASE_URL: ${EXAMS_DATABASE_URL}
      EXAMS_DATABASE_USER: ${EXAMS_DATABASE_USER}
      EXAMS_DATABASE_PASSWORD: ${EXAMS_DATABASE_PASSWORD}
      EXAMS_GOOGLE_CLIENT_ID: ${EXAMS_GOOGLE_CLIENT_ID}
      EXAMS_GOOGLE_CLIENT_SECRET: ${EXAMS_GOOGLE_CLIENT_SECRET}
      EXAMS_REDIS_PASSWORD: ${EXAMS_REDIS_PASSWORD}
    links:
      - "database:database"

  solr:
    image: solr:8.4
    container_name: exams-solr
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
      - ./solr/configsets:/opt/solr/server/solr/configsets
    entrypoint:
      - solr-precreate
      - questions
      - /opt/solr/server/solr/configsets/questions

  worker:
    image: worker
    container_name: exams-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      EXAMS_DATABASE_URL: ${EXAMS_DATABASE_URL}
      EXAMS_DATABASE_USER: ${EXAMS_DATABASE_USER}
      EXAMS_DATABASE_PASSWORD: ${EXAMS_DATABASE_PASSWORD}
    links:
      - "database:database"

volumes:
  db-data:
  solr-data:
