DROP TABLE IF EXISTS TB_QUESTION;
DROP TABLE IF EXISTS TB_SUBJECT;
DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_QUESTION (
    ID NUMBER PRIMARY KEY,
    STATEMENT VARCHAR2(2000),
    TYPE VARCHAR(60),
    DELETED BOOLEAN,
    KEYWORDS VARCHAR(300),
    SUBJECT_ID NUMBER,
    AUTHOR_ID VARCHAR(30)
);

CREATE TABLE TB_SUBJECT (
    ID NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE TB_USER (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255)
);

INSERT INTO TB_USER (ID, NAME, SURNAME) VALUES ('100001', 'Bo-young', 'Park');
INSERT INTO TB_USER (ID, NAME, SURNAME) VALUES ('100002', 'Na-ra', 'Jang');

INSERT INTO TB_SUBJECT (ID, DESCRIPTION) VALUES (1, 'Subject');

INSERT INTO TB_QUESTION (ID, STATEMENT, TYPE, DELETED, KEYWORDS, SUBJECT_ID, AUTHOR_ID)
 VALUES (1, 'Statement 1', 'TRUE_OR_FALSE', false, 'Key 1; Key 2;', 1, '100001');

INSERT INTO TB_QUESTION (ID, STATEMENT, TYPE, DELETED, KEYWORDS, SUBJECT_ID, AUTHOR_ID)
 VALUES (2, 'Statement 2', 'TRUE_OR_FALSE', true, 'Key 9; Key 0;', 1, '100001');

INSERT INTO TB_QUESTION (ID, STATEMENT, TYPE, DELETED, KEYWORDS, SUBJECT_ID, AUTHOR_ID)
 VALUES (3, 'Statement 3', 'MULTIPLE_CHOICES', false, 'Key 7; Key 8;', 1, '100002');