DROP TABLE IF EXISTS TB_QUESTION;
DROP TABLE IF EXISTS TB_ALTERNATIVE;
DROP TABLE IF EXISTS TB_SUBJECT;
DROP TABLE IF EXISTS TB_USER;
DROP TABLE IF EXISTS TB_EXAM;
DROP TABLE IF EXISTS TB_EXAM_QUESTION;
DROP TABLE IF EXISTS TB_QUESTION_COMMENT;

CREATE TABLE TB_QUESTION (
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    STATEMENT VARCHAR(2000) NOT NULL,
    TYPE VARCHAR(60) NOT NULL,
    SOLUTION VARCHAR(3000),
    DELETED BOOLEAN NOT NULL,
    CORRECT_ANSWER VARCHAR(2000) NOT NULL,
    KEYWORDS VARCHAR(300),
    SUBJECT_ID NUMBER NOT NULL,
    AUTHOR_ID VARCHAR(30) NOT NULL
);

CREATE TABLE TB_ALTERNATIVE (
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    QUESTION_ID NUMBER NOT NULL
);

CREATE TABLE TB_SUBJECT (
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TB_USER (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PICTURE VARCHAR(2000)
);

CREATE TABLE TB_EXAM (
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    STARTS_AT TIMESTAMP NULL,
    ENDS_AT TIMESTAMP NULL,
    DELETED BOOLEAN NOT NULL,
    MOCK_TEST BOOLEAN NOT NULL,
    AUTHOR_ID VARCHAR(30) NOT NULL
);

CREATE TABLE TB_EXAM_QUESTION (
    EXAM_ID NUMBER,
    QUESTION_ID NUMBER
);

CREATE TABLE TB_QUESTION_COMMENT(
    ID NUMBER PRIMARY KEY AUTO_INCREMENT,
    MESSAGE VARCHAR(3000) NOT NULL,
    QUESTION_ID NUMBER NOT NULL,
    AUTHOR_ID VARCHAR(30) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);

CREATE SEQUENCE EXAM_SEQ_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
