name: Server Build

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '!README.md'
      - '.github/workflows/server-pipeline.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Prepare gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew :server:build :server:jacocoTestReport
      
      - name: Upload jacocoTestReport
        uses: actions/upload-artifact@v1
        with:
          name: Test Coverage Report
          path: server/build/reports/jacoco/test/html

      - name: Static Analysis
        env:
          EXAMS_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        run: ./gradlew :server:sonarqube --info
        
      - name: Docker Build Image
        run: cd server && docker build .
