name: build

on:
  push:
    branches:
      - master
    paths:
      - "/server"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Prepare gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport
      
      - name: Upload jacocoTestReport
        uses: actions/upload-artifact@v1
        with:
          name: jacocoTestReport
          path: build/jacoco/test.exec

      - name: Static Analysis
        env:
          EXAMS_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          EXAMS_SONAR_ORG:  ${{ secrets.SONAR_ORG }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew sonarqube
        
      - name: Docker Build
        run: docker-compose --log-level INFO up -d --build
