name: Worker Build

on:
  push:
    branches:
      - master
    paths:
      - 'worker/**'
      - '!README.md'
      - '.github/workflows/worker-pipeline.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Prepare gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew :worker:build :worker:jacocoTestReport

      - name: Static Analysis
        env:
          EXAMS_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        run: ./gradlew :worker:sonarqube --info
        
      - name: Docker Build Image
        run: cd worker && docker build .
